- README.md
- app/src/main/java/uk/gov/android/authentication/AppAuthSession.kt
- app/src/main/java/uk/gov/android/authentication/AuthenticationError.kt
- app/src/main/java/uk/gov/android/authentication/LoginSession.kt
- app/src/main/java/uk/gov/android/authentication/LoginSessionConfiguration.kt
- Add enums for some configuration fields
- Add custom error, `AuthenticationError`
- Remove init function as can pass context into constructor Resolves: DCMAW-7374
> DCMAW:77374 - feat: Refactor Login Session

- .github/dependabot.yml
- gradle/libs.versions.toml
https://govukverify.atlassian.net/browse/DCMAW-7607
Adds dependabot.yml file to the repo, so that dependency updates are automatically triggered for GitHub actions and Gradle.
Also updates some dependency versions.
> DCMAW-7607: Add dependabot config

- app/build.gradle.kts
> fix: Fix pom publishing

- app/src/main/java/uk/gov/android/authentication/AppAuthSession.kt
- app/src/main/java/uk/gov/android/authentication/TokenResponse.kt
- config/styles/config/vocabularies/Base/accept.txt
- Align with expected token return
- use value instead of name of response type
- fix vale setup
Resolves: DCMAW-7624
> feat: Change TokenResponse

- buildLogic/plugins/src/main/kotlin/sonarqube-root-config.gradle.kts
- config/actions/sonar-analysis/action.yml
Update sonar configs
https://govukverify.atlassian.net/browse/DCMAW-8407
> Update sonar configs

- .github/workflows/on_pull_request.yml
- config/actions/sonar-analysis/action.yml
https://govukverify.atlassian.net/browse/DCMAW-7543
This PR adds a conditional step in the Sonar action file, to check the result of the quality gate scan.
> DCMAW-7543: Add Sonar gate quality check to PR workflow

- app/src/main/java/uk/gov/android/authentication/AppAuthSession.kt
- app/src/main/java/uk/gov/android/authentication/LoginSessionConfiguration.kt
[Ticket DCMAW-9390 ](https://govukverify.atlassian.net/browse/DCMAW-9390)
Add persistent session id to the AuthConfig
> DCMAW-9390 Add persistent session id to the AuthConfig

- app/src/androidTest/java/uk/gov/android/authentication/AppAuthSessionTest.kt
> fix: DCMAW-9390 setting persistent

- app/build.gradle.kts
- app/src/androidTest/AndroidManifest.xml
- app/src/androidTest/java/uk/gov/android/authentication/AppAuthPresentTest.kt
- app/src/androidTest/java/uk/gov/android/authentication/AppAuthSessionTest.kt
- app/src/androidTest/java/uk/gov/android/authentication/LoginSessionConfigurationTest.kt
- app/src/androidTest/java/uk/gov/android/authentication/LoginSessionConfigurationUtilTest.kt
- app/src/androidTest/java/uk/gov/android/authentication/TestActivity.kt
- app/src/androidTest/java/uk/gov/android/authentication/TokenResponseUtilTest.kt
- app/src/androidTest/java/uk/gov/android/authentication/openid/TestValues.kt
- app/src/main/java/uk/gov/android/authentication/AppAuthSession.kt
- app/src/main/java/uk/gov/android/authentication/AuthenticationError.kt
- app/src/main/java/uk/gov/android/authentication/LoginSessionConfiguration.kt
- app/src/main/java/uk/gov/android/authentication/LoginSessionConfigurationUtil.kt
- app/src/main/java/uk/gov/android/authentication/TokenResponse.kt
- app/src/main/java/uk/gov/android/authentication/TokenResponseUtil.kt
- app/src/test/java/uk/gov/android/authentication/AuthenticationErrorTest.kt
- app/src/test/java/uk/gov/android/authentication/TokenResponseTest.kt
- gradle/libs.versions.toml
**Ticket Link:** [DCMAW 9420](https://govukverify.atlassian.net/browse/DCMAW-9420)
**Description Of Changes:** 
I have focused on getting the test coverage up, and not on making the code good. I didn't want to change the public facing API, so there are a lot of small pure static functions in order to test paths, ideally we would refactor some pre-existing classes to better encapsulate these (both Util files shouldn't have to exist).
There is also some small parts that aren't being used (in this project) and can possibly be deleted, but we would need to check the other projects as they are public.
**Evidence:**
- [DCMAW-9420-JacocoConnectedReport.pdf](https://github.com/user-attachments/files/16725829/DCMAW-9420-JacocoConnectedReport.pdf)
**Documentation:** No Documentation
**Definition Of …
> DCMAW 9420 Improve sonar test coverage

- app/src/androidTest/java/uk/gov/android/authentication/integrity/FirebaseClientAttestationManagerTest.kt
- app/src/main/java/uk/gov/android/authentication/integrity/FirebaseClientAttestationManager.kt
- app/src/main/java/uk/gov/android/authentication/integrity/appcheck/AppChecker.kt
- app/src/main/java/uk/gov/android/authentication/integrity/model/AppCheckToken.kt
- handle response from FirebaseAppCheck
- update tests
> feat: Add functionality for the FirebaseAppCheck call

- app/src/main/java/uk/gov/android/authentication/integrity/FirebaseClientAttestationManager.kt
- app/src/main/java/uk/gov/android/authentication/integrity/appcheck/AppChecker.kt
- app/src/main/java/uk/gov/android/authentication/login/AppAuthSession.kt
- remove additional parameters as it was breaking the login flow and those won't be needed for now
Resolves: DCMAW-10312
> fix: Remove breaking change

- .github/workflows/on_pull_request.yml
- .github/workflows/on_push-main.yml
Pin existing workflows to Ubuntu 22
> DCMAW-10545 Change runs on to ubuntu-22.04

- gradle/libs.versions.toml
> fix: update agp

- build.gradle.kts
[//]: # (e.g. "- Create 'androidLibrary' Gradle module.")
N/a
Resolves: DCMAW-11313
> build: Update `SdkVersions` target and compile to API 35

- config/android/lint.xml
- gradle/libs.versions.toml
- localauth/build.gradle.kts
- localauth/src/main/java/uk/gov/android/localauth/ui/settings/GoToSettingScreen.kt
- localauth/src/main/java/uk/gov/android/localauth/ui/settings/GoToSettingsAnalyticsViewModel.kt
- localauth/src/main/res/values-cy/strings.xml
- localauth/src/main/res/values/screen_ids.xml
- localauth/src/main/res/values/strings.xml
- localauth/src/test/java/uk/gov/android/localauth/LocalAuthManagerTest.kt
- localauth/src/test/java/uk/gov/android/localauth/ui/BiometricsUiManagerTest.kt
- localauth/src/test/java/uk/gov/android/localauth/ui/settings/GoToSettingsAnalyticsViewModelTest.kt
- localauth/src/test/java/uk/gov/android/localauth/ui/settings/GoToSettingsScreenTest.kt
- Add numbered list to 'Go To Settings' screen
- update copy
- add analytics events for screen and button clicks
DCMAW-12608
https://github.com/user-attachments/assets/9169de81-cdbb-482d-ba41-ea9367e7e18e
https://github.com/user-attachments/assets/0fa4cad4-2b22-4476-b351-59271f4c717e
DCMAW-12700
https://github.com/user-attachments/assets/c3b5e6bc-6fff-48b0-853f-d4bd718f18eb
Logs:
```
2025-04-29 17:10:41.586 26066-26066 FirebaseAnalyticsLogger uk.gov.onelogin.build                D  Should log event: true
2025-04-29 17:10:41.588 26066-26066 FirebaseAnalyticsLogger uk.gov.onelogin.build                D  Firebase event sent with: Bundle[{language=en, screen_class=edc06a88-b779-4a17-9ed6-7a9c4103c290, saved_doc_type=undefined, taxonomy_level1=one login mobile application, …
```
> feat: DCMAW-12608 update go to settings

- gradle/libs.versions.toml
- localauth/src/main/java/uk/gov/android/localauth/ui/optin/BioOptInScreen.kt
- localauth/src/test/java/uk/gov/android/localauth/ui/settings/GoToSettingsScreenTest.kt
**No ticket**
**Description:**
- update to the latest ui version to allow the one-login app to use the same one
**Checklist:**
> build: Update common UI to v7.25.1 (latest)

- localauth/src/main/java/uk/gov/android/localauth/LocalAuthManager.kt
- localauth/src/main/java/uk/gov/android/localauth/LocalAuthManagerImpl.kt
- localauth/src/test/java/uk/gov/android/localauth/LocalAuthManagerTest.kt
- add function to enable checking if biometrics are available and enabled
- add functionality to enable toggling local pref to be set to biometrics or passcode
Resolves: DCMAW-12998, DCMAW-13060
> feat: Add functionality for the biometrics toggle

- .github/workflows/on_pull_request.yml
- .github/workflows/on_push-main.yml
- update to latest pipeline version, where the gradle cache is automatically enabled
- manually disabled gradle cache
> ci: Update to latest pipeline version and disable gradle cached 

- app/src/androidTest/java/uk/gov/android/authentication/login/AppAuthSessionTest.kt
- app/src/main/java/uk/gov/android/authentication/login/AppAuthSession.kt
- app/src/main/java/uk/gov/android/authentication/login/AuthenticationError.kt
- app/src/main/java/uk/gov/android/authentication/login/LoginSession.kt
- app/src/test/java/uk/gov/android/authentication/login/AuthenticationErrorTest.kt
Fix as part of [DCMAW-11137](https://govukverify.atlassian.net/browse/DCMAW-11137)
[DCMAW-11137]: https://govukverify.atlassian.net/browse/DCMAW-11137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add status code to AuthenticationError

- localauth/src/main/res/values-cy/strings.xml
- localauth/src/main/res/values/strings.xml
[Tutorial for writing good descriptions]: https://cbea.ms/git-commit/
[//]: # (Be mindful that the PR title also needs to follow conventional commit standards)
[//]: # (e.g. "- Create 'androidLibrary' Gradle module.")
https://github.com/user-attachments/assets/335b97ae-07a9-4c12-97d4-c64a9803f152
[//]: # (Screenshots / uploaded videos go here)
[Sonar cloud report]: https://sonarcloud.io/project/overview?id=di-mobile-android-ui
[Accessibility considerations]: https://developer.android.com/guide/topics/ui/accessibility/testing
> feat: Remove Wallet references with documents on `GoToSettingsScreen`

- gradle/libs.versions.toml
- localauth/src/main/java/uk/gov/android/localauth/ui/optin/BioOptInAnalyticsViewModel.kt
- localauth/src/main/java/uk/gov/android/localauth/ui/optout/BioOptOutAnalyticsViewModel.kt
- localauth/src/main/java/uk/gov/android/localauth/ui/settings/GoToSettingsAnalyticsViewModel.kt
- localauth/src/test/java/uk/gov/android/localauth/ui/optin/BioOptInAnalyticsViewModelTest.kt
- localauth/src/test/java/uk/gov/android/localauth/ui/optin/BioOptInScreenTest.kt
- localauth/src/test/java/uk/gov/android/localauth/ui/optout/BioOptOutAnalyticsViewModelTest.kt
- localauth/src/test/java/uk/gov/android/localauth/ui/settings/GoToSettingsAnalyticsViewModelTest.kt
- localauth/src/test/java/uk/gov/android/localauth/ui/settings/GoToSettingsScreenTest.kt
Amend GA Taxonomy levels
[DCMAW-11129]: https://govukverify.atlassian.net/browse/DCMAW-11129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Amend taxonomy values for GA events

- localauth/src/main/java/uk/gov/android/localauth/ui/optout/BioOptOutAnalyticsViewModel.kt
- localauth/src/main/java/uk/gov/android/localauth/ui/settings/GoToSettingsAnalyticsViewModel.kt
- localauth/src/main/res/values/strings.xml
- localauth/src/test/java/uk/gov/android/localauth/ui/optin/BioOptInAnalyticsViewModelTest.kt
- localauth/src/test/java/uk/gov/android/localauth/ui/optout/BioOptOutAnalyticsViewModelTest.kt
- localauth/src/test/java/uk/gov/android/localauth/ui/settings/GoToSettingsAnalyticsViewModelTest.kt
- localauth/src/test/java/uk/gov/android/localauth/ui/settings/GoToSettingsScreenTest.kt
- localauth/src/test/java/uk/gov/android/localauth/utils/GAUtils.kt
Change analytics events to Error for BioOptOutScreen and GoToSettingsScreen
Check is_error parameter in tests
[DCMAW-14533]: https://govukverify.atlassian.net/browse/DCMAW-14533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Change analytics events

- gradle/libs.versions.toml
- localauth/src/test/java/uk/gov/android/localauth/utils/BaseScreenshotTest.kt
> feat: Update to use GdsTheme v2 (latest UI version 8.0.0)
